# Site settings
title: CoderDojo Luzern @ bbv

email: coderdojo.luzern@gmail.com
description: 'CoderDojo in Luzern'
baseurl: /
url: "https://coderdojoluzern.github.io" # the base hostname & protocol for your site
github_username:  CoderDojoLuzern

# Build settings
markdown: kramdown

exclude: ["bin", "bower_components", "jekyll", "node_modules", "obj", "styles/sass/*.*", "typings", "coderdojo-linz.*", "*.json", "app.*", "Gulpfile.js"]
