## YAML Template.
---
name: Welcome
main: com.bajupa.welcome.Welcome
version: 0.2.1
authors:
    - P. Bauer
description: A friendly plugin greeting now and then.
commands:
    sayhello:
        description: Says hello.
        usage: /sayhello